web: gunicorn ivr_master:app

worker: gunicorn sqlwrapper.py
worker: gunicorn QueryANI.py
worker: gunicorn FetchExistingBookings.py
worker: gunicorn FetchRoomsAvailabilityandPrice.py
worker: gunicorn UpdateCustomerLangSelected.py
worker: gunicorn FetchPromotionalMessage.py
worker: gunicorn CalculateTotalChargesAndRetrieveConfirmationNumber.py
worker: gunicorn UpdatedCustomerProfile.py
worker: gunicorn CancelCurrentbooking.py
worker: gunicorn SendSMS.py
worker: gunicorn SendEmailIVR.py
worker: gunicorn SendEmailIVRTEST.py
worker: gunicorn SignupExtranet.py
worker: gunicorn LoginExtranet.py
worker: gunicorn AvailableRoomCount.py
worker: gunicorn RoomList.py
worker: gunicorn RatesandAvailability.py
worker: gunicorn InsertRatesandAvailability.py
worker: gunicorn UpdateRatesandAvailability.py
worker: gunicorn AddDiscount.py
worker: gunicorn QueryDiscount.py
worker: gunicorn CheckDate.py
worker: gunicorn SendEmail.py
worker: gunicorn SendEmailANI.py
worker: gunicorn InsertRatesandAvailability.py
worker: gunicorn PromotionalCancelMessage.py
worker: gunicorn UpdateExistingBooking.py
worker: gunicorn InsertCustomerRoomBooking.py
worker: gunicorn ValidateConfirmationNumber.py
worker: gunicorn FetchBooking.py
worker: gunicorn phonenumber.py
worker: gunicorn InsertCancelPolicy.py
worker: gunicorn Insert_Ivr_Reservation.py
worker: gunicorn Getchannelcount.py
worker: gunicorn Getreservationcancelmodification.py
worker: gunicorn ExtranetConfiguration.py
worker: gunicorn Inserttwilioreservation.py
worker: gunicorn create_rate_plan.py
worker: gunicorn User_signup.py
worker: gunicorn DashboardReport.py
worker: gunicorn ImageUploadS3.py	
worker: gunicorn SendEmailWhatsapp.py
worker: gunicorn sendemailconfirmation.py
worker: gunicorn gupshupproof.py
